config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'users/search' => 'users#search', as: 'user_search'
  get 'friends/:id' => 'friends#index', as: 'friends'
  resources :users do
    resource :friends, only: [:create, :destroy, :update]
  end
  root to: "informations#index"
  get 'informations/favorites' => 'favorites#index', as: 'favorites'
  resources :informations do
    resource :favorites, only: [:create, :destroy]
  end
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followee, class_name: "User"
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  # フォロー申請するとき status: 0
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end

  # フォロー承認するとき status: 1
  def update
    current_user.approve(params[:user_id])
    redirect_to request.referer
  end

  # フォロー外すとき
  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end

  def index
    # byebug
    user = User.find(params[:id])
    # # 申請中リスト
    @applied_friends = user.applied_friends()
    @apply_friends = user.apply_friends()
    # # 友達リスト
    @myfriend_users = user.myfriend_users
  end

  # # フォロー一覧
  # def followings
  #   user = User.find(params[:user_id])
  #   @users = user.followings
  # end
  # # フォロワー一覧
  # def followers
  #   user = User.find(params[:user_id])
  #   @users = user.followers
  # end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/index.html.erb
<div class = "friends-mypage">
  <%= link_to "マイページに戻る", user_path("mypage"), method: :get %>
</div>
<div class = "friends">
  <div class = "follower-list">
    <h1>友達申請中リスト</h1>
    <div class = "friends-box">
      <% @apply_friends.each do |friend| %>
        <% user = friend.followee %>
        <%= user.nickname %>
        <%= link_to "　友達申請を外す", user_friends_path(user.id), method: :delete %>
        <br>
      <% end %>
    </div>
  </div>

  <div class = "followee-list">
    <h1>友達承認待ちリスト</h1>
    <div class = "friends-box">
      <% @applied_friends.each do |friend| %>
        <% user = friend.follower %>
        <%= user.nickname %>
        <%= link_to "　申請を許可する", user_friends_path(user.id), method: :patch %>
        <%= link_to "　申請を拒否する",  user_friends_path(user.id), method: :delete  %>
        <br>
      <% end %>
    </div>
  </div>

  <div class = "friends-list">
    <h1>友達リスト</h1>
    <div class = "friends-box">
      <% @myfriend_users.each do |user| %>
        <%= link_to user.nickname, user_path(user) %>
        <%= link_to "　絶交する",  user_friends_path(user.id), method: :delete  %>
        <br>
      <% end %>
    </div>
  </div>