config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'users/search' => 'users#search', as: 'user_search'
  get 'friends/:id' => 'friends#index', as: 'friends'
  resources :users do
    resource :friends, only: [:create, :destroy, :update]
  end
  root to: "informations#index"
  get 'informations/favorites' => 'favorites#index', as: 'favorites'
  resources :informations do
    resource :favorites, only: [:create, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :informations, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :group_users

  # フォローをした、されたの関係
  has_many :friends, class_name: "Friend", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_friends, class_name: "Friend", foreign_key: "followee_id", dependent: :destroy

  # 一覧画面で使う
  has_many :followings, through: :friends, source: :followee
  has_many :followers, through: :reverse_of_friends, source: :follower

  validates :nickname, presence: true
  # validates :nickname, presence: true, uniquness: true
  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: 'には英字と数字の両方を含めて設定してください'
  validates :prefecture_id, numericality: { other_than: 1 , message: "can't be blank"}
  validates :municipality, presence: true
  validates :address, presence: true
  # validates :latitude, presence: true
  # validates :longitude, presence: true

  def applied_friends()
    reverse_of_friends.where(status: 0)
  end

  def apply_friends()
    friends.where(status: 0)
  end

  def myfriend_users()
    users = []
    friends.where(status: 1).each do |friend|
      users << friend.followee
    end
    reverse_of_friends.where(status: 1).each do |friend|
      users << friend.follower
    end
    return users
  end

  def myfriend?(user)
    if friends.where(followee_id: user.id).exists?
      return friends.find_by(followee_id: user.id).status == 1
    elsif reverse_of_friends.where(follower_id: user.id).exists?
      return reverse_of_friends.find_by(follower_id: user.id).status == 1
    else
      return false
    end
  end

  # フォロー申請したときの処理
  def follow(user_id)
    friends.create(status: 0,followee_id: user_id)
  end
  # フォロー承認したときの処理
  def approve(user_id)
    reverse_of_friends.find_by(follower_id: user_id).update(status: 1)
  end

  # フォローを外すときの処理
  def unfollow(user_id)
    friends.find_by(followee_id: user_id).destroy if followings.exists?
    reverse_of_friends.find_by(follower_id: user_id).destroy if followers.exists?
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

  # 承認しているか判定
  def apply?(user)
    if followings.include?(user)
      return friends.find_by(followee_id: user.id).status
    end
    return -1
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def search
    if User.where(nickname: params[:search_word]).exists?
      @user = User.find_by(nickname: params[:search_word])

      if current_user == @user
        @informations = @user.informations.page(params[:page]).reverse_order
      else
        @informations = @user.informations.where(status: 1).page(params[:page]).reverse_order
      end
    else
      redirect_to user_path("mypage")
    end
  end

  def edit
    @user = current_user
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
   end
  end

  def show
    if params[:id] == "mypage"
      @user = current_user
    else
      @user = User.find(params[:id])
    end

    unless current_user == @user || current_user.myfriend?(@user)
      redirect_to user_path("mypage")
    end

    if current_user == @user
      @informations = @user.informations.page(params[:page]).reverse_order
    else
      @informations = @user.informations.where(status: 1).page(params[:page]).reverse_order
    end
  end

  def user_params
    params.require(:user).permit(:nickname, :email, :password, :prefecture_id, :municipality, :address, :latitude, :longitude)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/search.html.erb
<div class="user_header w_inner">
  <div class="user_logo">
    <%= link_to image_tag("idobata.png", class:"idobata-icon"), root_path %>
    <h1><%= "#{@user.nickname}さんのマイページ" %></h1>
  </div>
  <ul>
    <% if current_user.id == @user.id %>
      <li>
        <%= link_to "新規投稿", new_information_path, method: :get, class:
        "item-red-btn" %>
      </li>
      <li>
        <%= link_to "お気に入り", root_path, method: :get, class: "item-red-btn"
        %>
      </li>
      <li>
        <%= link_to "プロフィール編集", edit_user_path("mypage"), method: :get, class: "item-red-btn"
        %>
      </li>
      <li>
        <%= form_with url: user_search_path, method: :get,local: true  do |f| %>
          <%= f.text_field :search_word, placeholder: "ニックネーム入力", class: "search-btn" %>
          <%= f.submit "友達を検索"%>
        <% end %>
      </li>
    <% else %>
      <% if @user.myfriend?(current_user) %>
        <div  class="follow-btn">すでに友達です</div>
        <%= link_to "絶交する", user_friends_path(@user.id), method: :delete, class: "follow-btn" %>
      <% else %>
        <% if @user.apply?(current_user) == 0 %>
          <%= link_to "申請を承認する", user_friends_path(@user.id), method: :patch, class: "follow-btn" %>
          <%= link_to "申請を拒否する", user_friends_path(@user.id), method: :delete, class: "follow-btn" %>
        <% else %>
          <% if current_user.following?(@user) %>
            <%= link_to "友達申請を外す", user_friends_path(@user.id), method: :delete, class: "follow-btn" %>
          <% else %>
            <%= link_to "友達申請をする", user_friends_path(@user.id), method: :post, class: "follow-btn" %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </ul>
</div>
<div class="posts w_inner">
  <div><%= image_tag "teatime01.jpg", class:"teatime-img" %></div>
</div>

<% if current_user == @user || @user.myfriend?(current_user) %>
  <div class="post_list">
    <h2>投稿一覧</h2>
    <div class="post_block">
      <% @informations.each do |info| %>
          <div class="post">
            <% if info.images.attached? %>
              <%= image_tag info.images[0].variant(resize:'400x300').processed %> <br>
            <% else %>
              <%= image_tag "ido.png",size: '400x300' %>
            <% end %>
            <div class="title"><%= info.title %></div>
            <div class="explain"><%= info.category %></div>
            <%= link_to '詳細ページ', information_path(info), class: "show-page" %>
          </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="user_header w_inner">
  <div class="user_logo">
    <%= link_to image_tag("idobata.png", class:"idobata-icon"), root_path %>
    <h1><%= "#{@user.nickname}さんのマイページ" %></h1>
  </div>
  <ul>
    <% if current_user.id == @user.id %>
      <li>
        <%= link_to "新規投稿", new_information_path, method: :get, class:
        "item-red-btn" %>
      </li>
      <li>
        <%= link_to "お気に入り", favorites_path, method: :get, class: "item-red-btn"
        %>
      </li>
      <li>
        <%= link_to "プロフィール編集", edit_user_registration_path, method: :get, class: "item-red-btn"
        %>
      </li>
      <li>
        <%= link_to "友達一覧", friends_path(current_user), method: :get, class: "item-red-btn"
        %>
      </li>
      <li>
        <%= form_with url: user_search_path, method: :get,local: true  do |f| %>
          <%= f.text_field :search_word, placeholder: "ニックネーム入力", class: "search-btn" %>
          <%= f.submit "友達を検索"%>
        <% end %>
      </li>
    <% else %>
      <% if @user.myfriend?(current_user) %>
        <div  class="follow-btn">すでに友達です</div>
        <%= link_to "絶交する", user_friends_path(@user.id), method: :delete, class: "follow-btn" %>
      <% else %>
        <% if @user.apply?(current_user) == 0 %>
          <%= link_to "申請を承認する", user_friends_path(@user.id), method: :patch, class: "follow-btn" %>
          <%= link_to "申請を拒否する", user_friends_path(@user.id), method: :delete, class: "follow-btn" %>
        <% else %>
          <% if current_user.following?(@user) %>
            <%= link_to "友達申請を外す", user_friends_path(@user.id), method: :delete, class: "follow-btn" %>
          <% else %>
            <%= link_to "友達申請をする", user_friends_path(@user.id), method: :post, class: "follow-btn" %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </ul>
</div>
<div class="posts w_inner">
  <div><%= image_tag "teatime01.jpg", class:"teatime-img" %></div>
  <div class="post_list">
    <h2>投稿一覧</h2>
    <div class="post_block">
      <% @informations.each do |info| %>
        <% if current_user == info.user || (current_user.myfriend?(info.user) && info.status == 1)%>
          <div class="post">
            <% if info.images.attached? %>
              <%= image_tag info.images[0].variant(resize:'400x300').processed %> <br>
            <% else %>
              <%= image_tag "ido.png",size: '400x300' %>
            <% end %>
            <div class="title"><%= info.title %></div>
            <div class="explain"><%= info.category %></div>
            <%= link_to '詳細ページ', information_path(info), class: "show-page" %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
<div class="page">
  <%= paginate @informations %>
</div>