config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'users/search' => 'users#search', as: 'user_search'
  get 'friends/:id' => 'friends#index', as: 'friends'
  resources :users do
    resource :friends, only: [:create, :destroy, :update]
  end
  root to: "informations#index"
  get 'informations/favorites' => 'favorites#index', as: 'favorites'
  resources :informations do
    resource :favorites, only: [:create, :destroy]
  end
end

app/models/information.rb
class Information < ApplicationRecord

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :group_informations
  has_many_attached :images

  def favorited?(user)
    favorites.where(user_id: user.id).exists?
  end

  enum category: {幼稚園・保育園:0, 学校:1, 習い事:2, 店舗:3, 施設:4, 病院:5, 理髪店・美容室:6, サービス:7, その他:8 }

  validates :title,       presence: true
  validates :category,    presence: true
  # validates :image,       presence: true
  validates :text,        presence: true
  validates :status,      presence: true
end

app/controllers/informations_controller.rb
class InformationsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_information, only: [:edit, :show]

  def index
  end

  def new
    @information = Information.new
  end

  def create
    @information = Information.new(information_params)
    if @information.save
      redirect_to user_path("mypage")
    else
      render :new
    end
  end

  def destroy
    information = Information.find(params[:id])
    if information.user == current_user
      information.destroy
    end
    redirect_to user_path("mypage")
  end

  def edit
    unless @information.user == current_user
      redirect_to user_path("mypage")
    end
  end

  def update
    information = Information.find(params[:id])
    if information.user == current_user
      information.update(information_params)
    end
    redirect_to information_path(information)
  end

  def show
    # フレンドか判定
    # if current_user.friends.find_by(information.user).status == 0
    #   redirect_to user_path("mypage")
    # end
    unless current_user == @information.user || current_user.myfriend?(@information.user)
      redirect_to user_path("mypage")
    end
    # # params
    # # params[:user_id]
    # @information = Information.find(34)
    # @information = Information.find_by(title: "gtkww")
  end

  private
  def information_params
    data = params.require(:information).permit(:title, :category, :text, :status, images: []).merge(user_id: current_user.id)
    data[:category] = data[:category].to_i
    return data
  end

  def set_information
    @information = Information.find(params[:id])
  end
end

app/helpers/informations_helper.rb
module InformationsHelper
end

app/views/informations/edit.html.erb
<%# cssは商品出品のものを併用しています。
app/assets/stylesheets/informations/new.css %>

<div class="contents row">
  <div class="information_new">
    <h1>
      <%= link_to root_path do %>
        <%= image_tag "idobata.png", class:"info-img" %>
      <% end %>
    </h1>
    <h2>投稿内容の編集</h2>
    <%= form_with(model: @information, url: information_path,local: true, class:"info") do |f|%>

      <div class="title">
        <%= f.label :title, "タイトル" %><br />
        <%= f.text_field :title, placeholder: "例：○○病院、□□幼稚園", class: "info info-title" %>
      </div>

      <div class="category">
        <%= f.label :category, "カテゴリー" %><br />
        <%= f.select :category, options_for_select(Information.categories), {prompt: "---"}, class: "info info-category"%>
      </div>

      <div class="image">
        <%= f.label :images, "参考画像" %><br />
        <%= f.file_field :images, multiple: true, class: "info info-image" %>
      </div>

      <div class="text">
        <%= f.label :text, "情報内容" %><br />
        <%= f.text_area :text, rows: 10, placeholder: "【HPのURL】


【スケジュール】


【〇〇費】


【良いところ】


【おすすめ】


", class: "info info-text" %>
      </div>

      <div class="btn">
        <%= f.submit "変更する", class: "info info-btn"%>
      </div>
    <% end %>
  </div>
</div>

app/views/informations/index.html.erb
<div id="home" class="big-bg">
  <header class="page-header wrapper">
    <h1>
      <%= link_to root_path do %>
        <%= image_tag "idobata.png" ,class:"idobata-img" %>
      <% end %>
    </h1>

    <% if user_signed_in? %>
    <nav>
      <ul class="main-nav">
        <li><%= link_to "マイページ", user_path("mypage"), method: :get, class: "mypage-btn" %></li>
        <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "logout-btn" %></li>
      </ul>
    </nav>
    <% else %>
    <nav>
      <ul class="main-nav">
        <li><%= link_to "ログイン", new_user_session_path, method: :get, class: "login-btn" %></li>
        <li><%= link_to "新規登録", new_user_registration_path, method: :get, class: "new-registration-btn" %></li>
      </ul>
    </nav>
    <% end %>
  </header>

  <div class="home-content wrapper">
    <h2 class="page-title">IDOBATA</h2>
    <p class="sub-title">お茶会で聞いた情報を友達と共有できるアプリ</p>
  </div>

</div>

app/views/informations/new.html.erb
<div class="contents row">
  <div class="information_new">
    <h1>
      <%= link_to root_path do %>
        <%= image_tag "idobata.png", class:"info-img" %>
      <% end %>
    </h1>
    <h2>新規投稿</h2>
    <%= form_with(model: @information, url: informations_path,local: true, class:"info") do |f|%>

      <div class="title">
        <%= f.label :title, "タイトル" %><br />
        <%= f.text_field :title, placeholder: "例：○○病院、□□幼稚園", class: "info info-title" %>
      </div>

      <div class="category">
        <%= f.label :category, "カテゴリー" %><br />
        <%= f.select :category, options_for_select(Information.categories), {prompt: "---"}, class: "info info-category"%>
      </div>

      <div class="image">
        <%= f.label :images, "参考画像" %><br />
        <%= f.file_field :images, multiple: true, class: "info info-image" %>
      </div>

      <div class="text">
        <%= f.label :text, "情報内容" %><br />
        <%= f.text_area :text, rows: 10, value: "【HPのURL】


【スケジュール】


【〇〇費】


【良いところ】


【おすすめ】


", class: "info info-text" %>
      </div>

      <div class="btn">
        <%= f.submit "投稿する", class: "info info-btn"%>
      </div>
    <% end %>
  </div>
</div>

app/views/informations/show.html.erb
<div class="info-show">
  <div class="info-box">
    <h2 class="title">
      <%= @information.title %>
    </h2>

    <div class="info-show">
      <% if @information.images.attached? %>
        <% @information.images.each do |image| %>
          <%= image_tag image.variant(resize:'400x300').processed %> <br>
        <% end %>
      <% else %>
        <%= image_tag "ido.png", class:"info-show-img" %>
      <% end %>
      <div class="info-show-category"><%= @information.category %></div>
      <div class="info-show-text"><%= @information.text %></div>
    </div>

    <div class="favorite">
      <div class="favorite-btn">
        <% if @information.favorited?(current_user) %>
          <%# 一致するレコードが存在する＝すでにいいね済みの場合はdestroyアクションへ %>
          <%= link_to information_favorites_path(@information.id), method: :delete do %>
            <span style="color:red;">❤︎</span>
          <% end %>
        <% else %>
          <%# 一致するレコードが存在しない＝まだいいねしていない場合はcreateアクションへ %>
          <%= link_to information_favorites_path(@information.id), method: :post do %>
            <span>❤︎</span>
          <% end %>
        <% end %>
      </div>
    </div>

    <% if current_user.id == @information.user_id %>
      <%= link_to "情報の編集", edit_information_path, method: :get, class: "info-edit" %>
      <p class="or-text">or</p>
      <%= link_to "削　除", information_path(@information.id), method: :delete, class:"info-destroy" %>
      <div class = "share">
        <%= form_with(model: @information, url: information_path,local: true, class:"share") do |f|%>
          <%= f.hidden_field :status, :value => 1 %>
          <%= f.submit "共有", class: "share-btn"%>
        <% end %>

        <%= form_with(model: @information, url: information_path,local: true, class:"share") do |f|%>
          <%= f.hidden_field :status, :value => 0 %>
          <%= f.submit "非共有", class: "unshare-btn"%>
        <% end %>
      </div>
    <% end %>

    <div>
      <%= link_to "マイページに戻る", user_path("mypage"), method: :get, class: "mypage-btn" %>
    </div>

  </div>
</div>